videos<-read.csv('C:/Users/sshss-pc/Desktop/project/CaptainU/videos.csv', header = TRUE)
sumvideos<-function(df){
  row<-nrow(df)
  result<-data.frame(rep(NA,row),rep(NA,row),rep(NA,row))
  names(result)<-c("Athlete_id","Sum","update")
  result[1,1]<-df[1,1]
  result[1,2]<-1
  result[1,3]<-as.character(df[1,4])
  current<-1
  for(n in 2:row){
    if(df[n,1]==df[n-1,1]){
      result[current,2]<-result[current,2]+1
      x<-as.POSIXct(df[n,4])
      y<-as.POSIXct(df[n-1,4])
      if(x>y){
        result[current,3]<-as.character(df[n,4])
      }
    }
    if(df[n,1]!=df[n-1,1]){
      current<-current+1
      result[current,1]<-df[n,1]
      result[current,2]<-1
      result[current,3]<-as.character(df[n,4])
    }
  }
  return(result)
}
videosum<-sumvideos(videos)
relationsum<-relationsum[1:332699,]
write.csv(relationsum,"C:/Users/sshss-pc/Desktop/videosum.csv")